[zulip.g0v]
    #Log in to the Zulip server.
    #Navigate to Settings () -> Your bots -> Add a new bot.
    #Select Generic for bot type, fill out the form and click on Create bot.
    #Token is the API key, you've got when creating the bot
    # Token="" # Set with env var MATTERBRIDGE_ZULIP_G0V_TOKEN

    #Login is the Username of the bot you've got when creating the bot
    # Login="" # Set with env var MATTERBRIDGE_ZULIP_G0V_LOGIN

    #The URL of your zulip server
    Server="https://g0v.zulipchat.com"

    RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[slack]
    [slack.chris-test-slack]
        # Token="" # Set with env var MATTERBRIDGE_SLACK_CHRIS_TEST_SLACK_TOKEN
        RemoteNickFormat="{PROTOCOL} - @{NICK}"

## GATEWAYS

[[gateway]]
    name="general-gateway"
    enable=true

	[[gateway.inout]]
	    account="zulip.g0v"
	    channel="general/topic:slack-bridge"

	[[gateway.inout]]
	    account="slack.chris-test-slack"
	    channel="general"

[[gateway]]
    name="covid19-gateway"
    enable=true

	[[gateway.inout]]
	    account="zulip.g0v"
	    channel="covid19/topic:slack-bridge"

	[[gateway.inout]]
	    account="slack.chris-test-slack"
	    channel="covid19"

[[gateway]]
    name="vaccine-gateway"
    enable=true

	[[gateway.inout]]
	    account="zulip.g0v"
	    channel="vaccine/topic:slack-bridge"

	[[gateway.inout]]
	    account="slack.chris-test-slack"
	    channel="vaccine"

[[gateway]]
    name="rand0m-gateway"
    enable=true

	[[gateway.inout]]
	    account="zulip.g0v"
	    channel="rand0m/topic:slack-bridge"

	[[gateway.inout]]
	    account="slack.chris-test-slack"
	    channel="rand0m"
